name: Run Comparison Script
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      firstBranchName:
        description: 'First branch name.'
        default: 'main'
        required: true
      secondBranchName:
        description: 'Second branch name.'
        default: 'main'
        required: true

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout main repo.
          uses: actions/checkout@v3.3.0
        - run: |
                  date > generated.txt
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "generated"
                  git push

        - run: |
              git merge-base main main2
              git config user.name github-actions
              git config user.email github-actions@github.com
          id: find_common_ancestor

        - uses: actions/checkout@v3.3.0
          with:
            ref: ${{ inputs.firstBranchName }}
            path: ${{ inputs.firstBranchName }}

        - uses: actions/checkout@v3.3.0
          with:
            ref: ${{ inputs.secondBranchName }}
            path: ${{ inputs.secondBranchName }}

#        - name: Find the most recent common ancestor.
#          id: find_common_ancestor
#          run: git merge-base main main2

        - name: Checkout the common ancestor.
          uses: actions/checkout@v3.3.0
          with:
            ref: ${{ steps.find_common_ancestor.outputs.* }}
            path: base
          
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        - name: Make gradlew executable
          run: chmod +x ./build/gradlew
          
        - name: Build with Gradle
          env: # Or as an environment variable
           SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
          run: cd build; ./gradlew runComparison -PfirstBranch=${{ inputs.firstBranchName }} -PsecondBranch=${{ inputs.secondBranchName }} --info --stacktrace --build-cache
       
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.4.1
          with:
            folder: report # The folder the action should deploy.
